[package]
name = "math_vector"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
rand = "0.9.0"

[profile.profiling]
inherits = "release"
debug = true